export const DEFAULT_SETTINGS = {
  company_name: "味源食品有限公司",
  greeting:
    "您好！欢迎联系味源食品。我是智能客服小源，可以帮您：\n① 查询产品价格、起订量、交期\n② 下单采购（配送 / 工厂自提）\n③ 了解付款与物流\n\n回复「产品」查看目录，或直接告诉我商品名称。需要人工请回复「转人工」。",
  business_hours: "周一至周六 08:30–18:00（法定节假日休息）",
  factory_email: "factory@weiyuan-foods.example.com",
  lead_time: "常温调味品现货 2–4 个工作日发货；冷冻食品 3–5 个工作日。大批量或定制请咨询。",
  delivery_info:
    "支持物流配送。常温件走物流，冷冻件走冷链。满 2000 元免基础运费（偏远地区除外），具体以跟单确认为准。",
  pickup_info: "工厂自提地址：江苏省南通市海安高新区味源路 88 号。请提前预约，凭订单号到成品仓提货。",
  payment_info: "支持对公转账。新客户款到发货；合作客户可申请月结，需提供营业执照与询证。",
};

export const PRODUCTS = [
  {
    name: "味源特级生抽",
    sku: "SS-001",
    price: 28,
    unit: "瓶",
    moq: 24,
    category: "调味汁",
    aliases: "生抽,酱油,特级生抽,浅色酱油",
    description: "黄豆酿造，色泽清亮，适合炒菜、凉拌与蘸食。500ml 玻璃瓶。",
  },
  {
    name: "味源老抽酱油",
    sku: "LS-002",
    price: 26,
    unit: "瓶",
    moq: 24,
    category: "调味汁",
    aliases: "老抽,上色酱油,红烧酱油",
    description: "红烧上色专用，酱香浓郁。500ml 玻璃瓶。",
  },
  {
    name: "味源陈酿香醋",
    sku: "CV-003",
    price: 18,
    unit: "瓶",
    moq: 24,
    category: "调味汁",
    aliases: "醋,香醋,陈醋,食醋",
    description: "三年陈酿，酸香柔和。500ml。",
  },
  {
    name: "纯芝麻香油",
    sku: "OI-004",
    price: 45,
    unit: "瓶",
    moq: 12,
    category: "调味汁",
    aliases: "香油,芝麻油,麻油,小磨香油",
    description: "小磨工艺，纯芝麻榨取。320ml。",
  },
  {
    name: "香辣豆瓣酱",
    sku: "SC-005",
    price: 22,
    unit: "瓶",
    moq: 24,
    category: "酱类",
    aliases: "辣酱,豆瓣,豆瓣酱,郫县风味",
    description: "郫县风味，炒菜提香。1kg 餐饮瓶。",
  },
  {
    name: "番茄沙司",
    sku: "TS-006",
    price: 15,
    unit: "瓶",
    moq: 36,
    category: "酱类",
    aliases: "番茄酱,ketchup,蕃茄酱",
    description: "儿童餐与西式简餐常用。340g。",
  },
  {
    name: "蚝油家庭装",
    sku: "OY-007",
    price: 32,
    unit: "瓶",
    moq: 12,
    category: "调味汁",
    aliases: "蚝油,蚝油膏",
    description: "蚝香醇厚，炒菜、凉拌、腌制皆宜。700g。",
  },
  {
    name: "猪肉白菜水饺",
    sku: "FD-101",
    price: 38,
    unit: "袋",
    moq: 20,
    category: "冷冻面点",
    aliases: "水饺,饺子,猪肉水饺,白菜水饺,冷冻水饺",
    description: "急冻锁鲜，约 500g / 20 只。需冷冻储运。",
  },
  {
    name: "韭菜鸡蛋水饺",
    sku: "FD-102",
    price: 36,
    unit: "袋",
    moq: 20,
    category: "冷冻面点",
    aliases: "韭菜水饺,鸡蛋水饺,素馅饺子",
    description: "鲜韭菜与鸡蛋馅。约 500g / 20 只。冷冻。",
  },
  {
    name: "黑芝麻汤圆",
    sku: "FT-201",
    price: 28,
    unit: "袋",
    moq: 30,
    category: "冷冻面点",
    aliases: "汤圆,芝麻汤圆,元宵",
    description: "传统黑芝麻馅，约 400g。冷冻。",
  },
  {
    name: "鲜虾馄饨",
    sku: "FW-301",
    price: 48,
    unit: "袋",
    moq: 15,
    category: "冷冻面点",
    aliases: "馄饨,虾馄饨,云吞,虾云吞",
    description: "含虾仁，皮薄馅大。约 400g。冷冻。",
  },
  {
    name: "冷冻春卷",
    sku: "FF-501",
    price: 42,
    unit: "盒",
    moq: 16,
    category: "冷冻面点",
    aliases: "春卷,炸春卷",
    description: "蔬菜鲜肉馅，油炸即食。12 只/盒。冷冻。",
  },
  {
    name: "山椒脆笋",
    sku: "SN-401",
    price: 12,
    unit: "袋",
    moq: 50,
    category: "休闲零食",
    aliases: "脆笋,笋干,山椒笋,辣笋",
    description: "开袋即食，微辣脆爽。80g。",
  },
  {
    name: "海苔薯片",
    sku: "SN-402",
    price: 9.9,
    unit: "袋",
    moq: 60,
    category: "休闲零食",
    aliases: "薯片,海苔,海苔片",
    description: "薄切马铃薯，海苔风味。70g。",
  },
  {
    name: "五香牛肉干",
    sku: "SN-403",
    price: 58,
    unit: "袋",
    moq: 10,
    category: "休闲零食",
    aliases: "牛肉干,牛肉,风干牛肉",
    description: "精选牛后腿，五香风干。120g。",
  },
  {
    name: "香辣虾片",
    sku: "SN-404",
    price: 15,
    unit: "袋",
    moq: 40,
    category: "休闲零食",
    aliases: "虾片,膨化虾片,辣虾片",
    description: "经典膨化虾片，香辣口味。90g。",
  },
];

export const FAQS = [
  {
    keywords: "营业时间,上班,几点,开门,工作时间,值班",
    question: "营业时间",
    answer: "",
  },
  {
    keywords: "交期,货期,发货,多久,周期,lead time,交货",
    question: "交期",
    answer: "",
  },
  {
    keywords: "配送,物流,运费,快递,冷链,送货",
    question: "配送",
    answer: "",
  },
  {
    keywords: "自提,到厂,提货,来拿,工厂地址,仓库",
    question: "自提",
    answer: "",
  },
  {
    keywords: "付款,转账,账期,月结,支付,对公",
    question: "付款",
    answer: "",
  },
  {
    keywords: "起订,最小订购,moq,起订量,最少买",
    question: "起订量",
    answer: "每款产品都有最小起订量（MOQ），详见商品信息。低于起订量需与跟单确认是否可拼单。",
  },
  {
    keywords: "发票,专票,普票,增值税",
    question: "发票",
    answer: "支持增值税普通发票与专用发票，下单后请提供开票资料，随货或次月统一开具。",
  },
  {
    keywords: "样品,试吃,试单,拿样",
    question: "样品",
    answer: "可申请付费样品，运费到付。样品金额可在首笔大宗订单中抵扣。请留下公司名与收件信息。",
  },
  {
    keywords: "储存,保质期,冷藏,冷冻,常温",
    question: "储存",
    answer: "调味品常温阴凉避光；冷冻面点需 -18℃ 以下储运，收到后请立即入冷冻库。保质期见包装。",
  },
];
