export const DEFAULT_SETTINGS = {
  company_name: "Aunty Hong",
  greeting: "Hi! You've reached Aunty Hong. I'm Hong, here to help with:\n1) Prices, stock and gift sets\n2) Placing an order or a corporate hamper\n3) Delivery, PayNow and lead time\n\nReply MENU for the catalogue, or just tell me what you're looking for (shrimp fries, belinjau, cookies, tea, noodles).\nOnline minimum is S$50. We have no walk-in shop — order here or on auntyhong.sg. For a person, reply HUMAN.",
  business_hours: "Mon–Sat 9:00am–6:00pm SGT (closed Sundays and public holidays).",
  factory_email: "kitchen@auntyhong.sg",
  lead_time: "Most snacks ship in 3–5 working days. CNY gift sets can take longer in peak season. We will confirm after the order.",
  delivery_info: "Islandwide delivery in Singapore. No walk-in retail at Aljunied — the kitchen is not a shop. We will confirm delivery charges with you.",
  pickup_info: "Collection by arrangement only at 1005 Aljunied Ave 5 #01-42, Singapore 389886. Not a walk-in store. Please wait for a confirmed slot.",
  payment_info: "PayNow, bank transfer, or checkout on auntyhong.sg. All sales are final; WhatsApp us at +65 9638 1788 if something arrives damaged.",
};

export const PRODUCTS = [
  {
    name: "Organic Handmade Noodles: Family Pack — Original (6pcs)",
    sku: "SQ5129790",
    price: 20.9,
    unit: "pack",
    moq: 1,
    category: "Organic Handmade Noodles",
    aliases: "Organic Handmade Noodles: Family Pack, Original (6pcs), noodles,organic noodles,family pack,mee",
    description: "Bring the family together for a feast with Aunty Hong's Organic Noodles: Family Pack! Ideal for steamboats, gatherings, or simply feeding a hungry crew, choose from 3 flavors: Original, Seaweed, and Beetroot. Stock up now and create memorable, delicious meals with ease!< Variant: Original (6pcs).",
    in_stock: 1,
  },
  {
    name: "Organic Handmade Noodles: Family Pack — Beetroot (6pcs)",
    sku: "SQ4272459",
    price: 22.9,
    unit: "pack",
    moq: 1,
    category: "Organic Handmade Noodles",
    aliases: "Organic Handmade Noodles: Family Pack, Beetroot (6pcs), noodles,organic noodles,family pack,mee",
    description: "Bring the family together for a feast with Aunty Hong's Organic Noodles: Family Pack! Ideal for steamboats, gatherings, or simply feeding a hungry crew, choose from 3 flavors: Original, Seaweed, and Beetroot. Stock up now and create memorable, delicious meals with ease!< Variant: Beetroot (6pcs).",
    in_stock: 1,
  },
  {
    name: "Organic Handmade Noodles: Family Pack — Seaweed (6pcs)",
    sku: "SQ7903531",
    price: 22.9,
    unit: "pack",
    moq: 1,
    category: "Organic Handmade Noodles",
    aliases: "Organic Handmade Noodles: Family Pack, Seaweed (6pcs), noodles,organic noodles,family pack,mee",
    description: "Bring the family together for a feast with Aunty Hong's Organic Noodles: Family Pack! Ideal for steamboats, gatherings, or simply feeding a hungry crew, choose from 3 flavors: Original, Seaweed, and Beetroot. Stock up now and create memorable, delicious meals with ease!< Variant: Seaweed (6pcs).",
    in_stock: 1,
  },
  {
    name: "Bundle of Joy",
    sku: "SQ1372738",
    price: 43.9,
    unit: "set",
    moq: 1,
    category: "CNY 2026 Gift Sets",
    aliases: "Bundle of Joy, bundle of joy,gift set,cny set,hamper",
    description: "A duo of our crowd favourites - crunchy strips of prawn crackers and the inimitable sweet spicy belinjau! The Bundle of Joy consists of: 1 Tin of Shrimp Fries <p da",
    in_stock: 1,
  },
  {
    name: "Lucky Duo",
    sku: "SQ9265799",
    price: 66.0,
    unit: "set",
    moq: 1,
    category: "CNY 2026 Gift Sets",
    aliases: "Lucky Duo, lucky duo,cookie gift",
    description: "Like the Chinese saying 'good things come in pairs', so do our cookies! Our Lucky Duo set includes two jars of artisanal cookies and snacks of your choosing - mix and match from our wide range of meticulously",
    in_stock: 1,
  },
  {
    name: "Spring Blossom Box",
    sku: "SQ3256324",
    price: 88.0,
    unit: "set",
    moq: 1,
    category: "CNY 2026 Gift Sets",
    aliases: "Spring Blossom Box, spring blossom,tingkat",
    description: "Introducing our sophisticated take on the beloved tingkat - Aunty Hong's Spring Blossom Box! A true embodiment of style and tradition, thoughtfully designed to house an assortment of our favourite Aunty Hong CN",
    in_stock: 0,
  },
  {
    name: "The Prosperity Mix",
    sku: "SQ6616475",
    price: 128.0,
    unit: "set",
    moq: 1,
    category: "CNY 2026 Gift Sets",
    aliases: "The Prosperity Mix, prosperity mix,hamper,gift box",
    description: "Ever wished someone gifted you a hamper filled with all your favourite snacks?? By popular demand, we are introducing an Aunty Hong's CNY essentials giftbox this year - The Prosperity Mix! A starter snack kit t",
    in_stock: 1,
  },
  {
    name: "Shrimp Fries | Prawn Crackers — Original - Golden Aunty Hong Tin",
    sku: "SQ0179319",
    price: 22.0,
    unit: "tin",
    moq: 1,
    category: "Halal-Certified Goodies",
    aliases: "Shrimp Fries | Prawn Crackers, Original - Golden Aunty Hong Tin, shrimp fries,prawn crackers,keropok udang,shrimp crackers,prawn,shrimp,gold tin",
    description: "A favourite among our team, Aunty Hong's signature Shrimp Fries are addicting crispy strips of prawn crackers fried in high quality coconut oil. While shrimp snacks often contain 10-15% of shrimp meat, our shrimp fries are made up of 40% shrimp meat for a robust shellfish flav Variant: Original - Golden Aunty Hong Tin.",
    in_stock: 1,
  },
  {
    name: "Shrimp Fries | Prawn Crackers — Refill Pack - Foil Bag",
    sku: "SQ7104161",
    price: 19.0,
    unit: "refill pack",
    moq: 1,
    category: "Halal-Certified Goodies",
    aliases: "Shrimp Fries | Prawn Crackers, Refill Pack - Foil Bag, shrimp fries,prawn crackers,keropok udang,shrimp crackers,prawn,shrimp,refill",
    description: "A favourite among our team, Aunty Hong's signature Shrimp Fries are addicting crispy strips of prawn crackers fried in high quality coconut oil. While shrimp snacks often contain 10-15% of shrimp meat, our shrimp fries are made up of 40% shrimp meat for a robust shellfish flav Variant: Refill Pack - Foil Bag.",
    in_stock: 1,
  },
  {
    name: "Sweet & Spicy Belinjau Keropok | Belinjo Crackers — Original - Orange Aunty Hong Tin",
    sku: "SQ6658375",
    price: 22.0,
    unit: "tin",
    moq: 1,
    category: "Halal-Certified Goodies",
    aliases: "Sweet & Spicy Belinjau Keropok | Belinjo Crackers, Original - Orange Aunty Hong Tin, belinjau,belinjo,emping,sweet spicy,orange tin",
    description: "Our Belinjau Keropok is a sweet and spicy snack that is extremely addicting! Made from the nuts of the Melinjo tree, we add a layer of homemade paste to our crackers to add a burst of umami flavour to them. Comes packaged in an Orange Aunty Hong Tin (17cm Diameter x Variant: Original - Orange Aunty Hong Tin.",
    in_stock: 1,
  },
  {
    name: "Sweet & Spicy Belinjau Keropok | Belinjo Crackers — Refill Pack - Foil Bag",
    sku: "SQ4839421",
    price: 19.0,
    unit: "refill pack",
    moq: 1,
    category: "Halal-Certified Goodies",
    aliases: "Sweet & Spicy Belinjau Keropok | Belinjo Crackers, Refill Pack - Foil Bag, belinjau,belinjo,emping,sweet spicy,orange tin",
    description: "Our Belinjau Keropok is a sweet and spicy snack that is extremely addicting! Made from the nuts of the Melinjo tree, we add a layer of homemade paste to our crackers to add a burst of umami flavour to them. Comes packaged in an Orange Aunty Hong Tin (17cm Diameter x Variant: Refill Pack - Foil Bag.",
    in_stock: 1,
  },
  {
    name: "Himalayan Salted Classic Belinjau Keropok | Emping Melinjo — Original - Red Aunty Hong Tin",
    sku: "SQ7484250",
    price: 20.0,
    unit: "tin",
    moq: 1,
    category: "Halal-Certified Goodies",
    aliases: "Himalayan Salted Classic Belinjau Keropok | Emping Melinjo, Original - Red Aunty Hong Tin, himalayan,salted belinjau,classic belinjau,vegetarian keropok,red tin",
    description: "Our Belinjau Keropok is fried with fragrant coconut oil to give it a crispy, golden crust, then sprinkled with Himalayan Salt for an added dimension of taste! We did the math - for every cracker, 5 belinjau fruits were smashed and mixed in to yield the perfect Himalayan Salted Variant: Original - Red Aunty Hong Tin.",
    in_stock: 1,
  },
  {
    name: "Himalayan Salted Classic Belinjau Keropok | Emping Melinjo — Refill Pack - Foil Bag",
    sku: "SQ8454806",
    price: 17.0,
    unit: "refill pack",
    moq: 1,
    category: "Halal-Certified Goodies",
    aliases: "Himalayan Salted Classic Belinjau Keropok | Emping Melinjo, Refill Pack - Foil Bag, himalayan,salted belinjau,classic belinjau,vegetarian keropok,red tin",
    description: "Our Belinjau Keropok is fried with fragrant coconut oil to give it a crispy, golden crust, then sprinkled with Himalayan Salt for an added dimension of taste! We did the math - for every cracker, 5 belinjau fruits were smashed and mixed in to yield the perfect Himalayan Salted Variant: Refill Pack - Foil Bag.",
    in_stock: 1,
  },
  {
    name: "Balinese White Fish Keropok — Original - Red Aunty Hong Tin",
    sku: "SQ5268830",
    price: 20.0,
    unit: "tin",
    moq: 1,
    category: "Premium Keropok",
    aliases: "Balinese White Fish Keropok, Original - Red Aunty Hong Tin, fish keropok,white fish,balinese",
    description: "We use the freshest Indonesian white fish to make our Balinese White Fish Keropok, frying them in high quality coconut oil to yield a cracker that is both healthy and satisfyingly crispy and flavourful. Unlike other fish Keropok that contain only 10-15% fish meat, our Variant: Original - Red Aunty Hong Tin.",
    in_stock: 1,
  },
  {
    name: "Balinese White Fish Keropok — Refill Pack - Foil Bag",
    sku: "SQ1386278",
    price: 17.0,
    unit: "refill pack",
    moq: 1,
    category: "Premium Keropok",
    aliases: "Balinese White Fish Keropok, Refill Pack - Foil Bag, fish keropok,white fish,balinese",
    description: "We use the freshest Indonesian white fish to make our Balinese White Fish Keropok, frying them in high quality coconut oil to yield a cracker that is both healthy and satisfyingly crispy and flavourful. Unlike other fish Keropok that contain only 10-15% fish meat, our Variant: Refill Pack - Foil Bag.",
    in_stock: 1,
  },
  {
    name: "Traditional Shrimp Keropok | Prawn Crackers — Original - Red Aunty Hong Tin",
    sku: "SQ4959890",
    price: 20.0,
    unit: "tin",
    moq: 1,
    category: "Halal-Certified Goodies",
    aliases: "Traditional Shrimp Keropok | Prawn Crackers, Original - Red Aunty Hong Tin, traditional shrimp,traditional prawn",
    description: "We take great care in preparing Aunty Hong's crispy and moorish Traditional Shrimp Keropok - we utilise quality ingredients to make them, frying them in high quality coconut oil after. While shrimp snacks often contain 10-15% of shrimp meat, our Traditional Shrimp Keropok are Variant: Original - Red Aunty Hong Tin.",
    in_stock: 1,
  },
  {
    name: "Traditional Shrimp Keropok | Prawn Crackers — Refill Pack - Foil Bag",
    sku: "SQ5931307",
    price: 17.0,
    unit: "refill pack",
    moq: 1,
    category: "Halal-Certified Goodies",
    aliases: "Traditional Shrimp Keropok | Prawn Crackers, Refill Pack - Foil Bag, traditional shrimp,traditional prawn",
    description: "We take great care in preparing Aunty Hong's crispy and moorish Traditional Shrimp Keropok - we utilise quality ingredients to make them, frying them in high quality coconut oil after. While shrimp snacks often contain 10-15% of shrimp meat, our Traditional Shrimp Keropok are Variant: Refill Pack - Foil Bag.",
    in_stock: 1,
  },
  {
    name: "Mini Traditional Shrimp Keropok | Prawn Crackers — Original - Red Aunty Hong Tin",
    sku: "SQ8776802",
    price: 20.0,
    unit: "tin",
    moq: 1,
    category: "Halal-Certified Goodies",
    aliases: "Mini Traditional Shrimp Keropok | Prawn Crackers, Original - Red Aunty Hong Tin, traditional shrimp,traditional prawn",
    description: "Aunty Hong's Traditional Shrimp Keropok made more snackable! We utilise quality ingredients to make them, frying them in high quality coconut oil after. While shrimp snacks often contain 10-15% of shrimp meat, our Traditional Shrimp Keropok are made up of 33% shrimp meat for a Variant: Original - Red Aunty Hong Tin.",
    in_stock: 1,
  },
  {
    name: "Mini Traditional Shrimp Keropok | Prawn Crackers — Refill Pack - Foil Bag",
    sku: "SQ3767211",
    price: 17.0,
    unit: "refill pack",
    moq: 1,
    category: "Halal-Certified Goodies",
    aliases: "Mini Traditional Shrimp Keropok | Prawn Crackers, Refill Pack - Foil Bag, traditional shrimp,traditional prawn",
    description: "Aunty Hong's Traditional Shrimp Keropok made more snackable! We utilise quality ingredients to make them, frying them in high quality coconut oil after. While shrimp snacks often contain 10-15% of shrimp meat, our Traditional Shrimp Keropok are made up of 33% shrimp meat for a Variant: Refill Pack - Foil Bag.",
    in_stock: 0,
  },
  {
    name: "Premium Prawn Rolls — Original - Reusable Glass Jar",
    sku: "SQ6541036",
    price: 20.0,
    unit: "jar",
    moq: 1,
    category: "Halal-Certified Goodies",
    aliases: "Premium Prawn Rolls, Original - Reusable Glass Jar, prawn rolls,shrimp rolls",
    description: "Aunty Hong's Premium Prawn Rolls get our team's top votes for favourite Chinese New Year snack. We make them with a traditional recipe that uses premium dried shrimps wrapped in a thin crispy skin and fried in high quality coconut oil so that you enjoy the full flavour without Variant: Original - Reusable Glass Jar.",
    in_stock: 1,
  },
  {
    name: "Tom Yum Goong Cashews — Original - Reusable Glass Jar",
    sku: "SQ8253671",
    price: 26.0,
    unit: "jar",
    moq: 1,
    category: "Nuts & Tidbits",
    aliases: "Tom Yum Goong Cashews, Original - Reusable Glass Jar, tom yum,cashews,cashew",
    description: "Good news for all Tom Yum lovers - our highly-anticipated Tom Yum Goong Cashews are here! Coated with generous layers of no-nonsense tom yum paste made from chili pepper, chili padi, lime leaves, lemongrass and lime - no cashew has been left unattended. Buy more than 1 jar at Variant: Original - Reusable Glass Jar.",
    in_stock: 1,
  },
  {
    name: "Japanese Baked Shiitake Mushroom Chips",
    sku: "SQ6650947",
    price: 24.0,
    unit: "tin",
    moq: 1,
    category: "Nuts & Tidbits",
    aliases: "Japanese Baked Shiitake Mushroom Chips, shiitake,mushroom chips,vegetarian chips",
    description: "Now this is a treat for vegetarians. Naturally sun-dried, lightly salted and then baked to perfection, our Japanese Baked Shiitake Mushroom Chips are the go-to option for those of you who are watching your diets, but still want something",
    in_stock: 1,
  },
  {
    name: "Osmanthus Long-Jing Tea",
    sku: "SQ3518117",
    price: 25.0,
    unit: "box",
    moq: 1,
    category: "Vegetarian-Friendly",
    aliases: "Osmanthus Long-Jing Tea, osmanthus,long jing,longjing,dragon well,green tea",
    description: "Prepared meticulously in a process known as 'scenting', tea masters stack layers of Long-Jing tea leaves with Osmanthus flowers to create a refreshing, mellow brew. Low in astringency and mildly sweet, the Osmanthus",
    in_stock: 1,
  },
  {
    name: "White Peach Oolong Tea",
    sku: "SQ6454540",
    price: 25.0,
    unit: "box",
    moq: 1,
    category: "Vegetarian-Friendly",
    aliases: "White Peach Oolong Tea, peach oolong,oolong,white peach",
    description: "The White Peach Oolong Tea is a perfect combination of the peach's lingering, fruity aroma with the inherent flavors of Oolong - creating an ideal duo for kicking off your day or calming your senses during the",
    in_stock: 1,
  },
  {
    name: "Sun Moon Lake Red Tea",
    sku: "SQ3171043",
    price: 25.0,
    unit: "box",
    moq: 1,
    category: "Vegetarian-Friendly",
    aliases: "Sun Moon Lake Red Tea, sun moon lake,red tea,black tea,ruby red",
    description: "Known as the most celebrated tea in Sun Moon Lake and nicknamed 'Ruby Red' by its cultivators, this tea is a combination of leaves from the assamica variety. Lighter, smooth, and naturally sweet, a soothing cup",
    in_stock: 1,
  },
  {
    name: "Handmade Melty Kuih Bangkit",
    sku: "SQ2500128",
    price: 28.0,
    unit: "tin",
    moq: 1,
    category: "Handmade CNY Cookies",
    aliases: "Handmade Melty Kuih Bangkit, kuih bangkit,kueh bangkit,bangkit",
    description: "You may have seen the classic Kuih Bangkit everywhere during the festivities, but there's nothing quite like Aunty Hong's Melty Kuih Bangkit! Handmade laboriously with hours of prepwork and cooking in the kitchen, it is then mixed with rich coconut milk to b",
    in_stock: 1,
  },
  {
    name: "Handmade Emping Belinjau Cookies",
    sku: "SQ6080815",
    price: 28.0,
    unit: "tin",
    moq: 1,
    category: "Handmade CNY Cookies",
    aliases: "Handmade Emping Belinjau Cookies, emping cookies,belinjau cookies",
    description: "Made from fresh Indonesian Melinjo nuts, this is an Aunty Hong Specialty that our founder grew up loving (and munching on). So well-loved by the community back in the olden days, it’s also known as Epic Emping - a nickname that matches its popularity! Slightly bitter but also",
    in_stock: 1,
  },
  {
    name: "Handmade Almond Butter Cookies",
    sku: "SQ6824172",
    price: 28.0,
    unit: "tin",
    moq: 1,
    category: "Handmade CNY Cookies",
    aliases: "Handmade Almond Butter Cookies, almond cookies,almond butter",
    description: "Our Handmade Almond Butter Cookie recipe is an original that has been tried and tested. These melt-in-your-mouth rounds are perfect as gifts, and we're sharing this recipe in hopes that it will remind you of the warmth of home, just as it does for us. Vegetarian-frie",
    in_stock: 0,
  },
  {
    name: "Handmade Cashew Butter Cookies",
    sku: "SQ8181462",
    price: 28.0,
    unit: "tin",
    moq: 1,
    category: "Handmade CNY Cookies",
    aliases: "Handmade Cashew Butter Cookies, cashew cookies,cashew butter",
    description: "Our Handmade Cashew Butter Cookies are rich, buttery and extremely addicting! This cookie recipe is an original that has been refined for many years, well loved by our family and friends. Vegetarian-friendly (contains eggs) Comes packaged in a Gold Aunty Hong Co",
    in_stock: 0,
  },
  {
    name: "Handmade Malty Cashew Bars",
    sku: "SQ2640375",
    price: 28.0,
    unit: "tin",
    moq: 1,
    category: "Handmade CNY Cookies",
    aliases: "Handmade Malty Cashew Bars, malty cashew,cashew bars",
    description: "Our love for cashew nuts inspired this popular snack that is traditionally made with ordinary peanuts. As with everything under the Aunty Hong name, we only make snacks that we love munching on! Not overwhelmingly sweet but just enough to satisfy a sweet tooth, these cas",
    in_stock: 1,
  },
];

export const FAQS = [
  {
    keywords: "hours,opening,open,close,when are you open,business hours",
    question: "hours",
    answer: "",
  },
  {
    keywords: "lead time,delivery time,how long,when will it arrive,ship,shipping time",
    question: "lead time",
    answer: "",
  },
  {
    keywords: "delivery,shipping,postage,deliver,islandwide,courier",
    question: "delivery",
    answer: "",
  },
  {
    keywords: "pickup,collect,self collect,walk-in,walk in,aljunied,visit,shop",
    question: "pickup",
    answer: "",
  },
  {
    keywords: "pay,payment,paynow,bank transfer,transfer",
    question: "payment",
    answer: "",
  },
  {
    keywords: "minimum,min order,moq,$50,50 dollars",
    question: "minimum",
    answer: "Our website minimum order is S$50. Individual SKUs can be ordered from 1 unit; we will remind you if the cart is under S$50.",
  },
  {
    keywords: "refund,return,exchange,damaged",
    question: "returns",
    answer: "All sales are final and non-refundable. If something arrives damaged, WhatsApp us at +65 9638 1788 with photos and we will help.",
  },
  {
    keywords: "halal",
    question: "halal",
    answer: "Many of our keropok and snacks are halal-certified. Ask about a specific SKU and I will check.",
  },
  {
    keywords: "vegetarian,veg,eggs",
    question: "vegetarian",
    answer: "Several items are vegetarian-friendly (some cookies contain eggs). Himalayan salted belinjau, shiitake chips, teas, noodles and several cookies are labelled vegetarian.",
  },
  {
    keywords: "address,where are you,location",
    question: "address",
    answer: "Kitchen: 1005 Aljunied Ave 5 #01-42, Singapore 389886. No walk-in retail — please order via WhatsApp or auntyhong.sg.",
  },
  {
    keywords: "whatsapp,contact,phone",
    question: "contact",
    answer: "WhatsApp +65 9638 1788. Instagram @auntyhong.sg. Website https://www.auntyhong.sg",
  },
];
